# Generated by Django 4.1.4 on 2023-01-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_profile_user_profile_date_profile_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('description', models.TextField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(default='', upload_to='main_app/static/product-images')),
                ('sku', models.IntegerField()),
            ],
        ),
    ]
