# Generated by Django 4.1.4 on 2023-01-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_image',
            field=models.ImageField(default='', upload_to='main_app/static/product-images/'),
        ),
    ]
