# Generated by Django 4.1.4 on 2023-01-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_rename_name_profile_first_name_profile_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='roles',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Merchant', 'Merchant')], max_length=50, null=True),
        ),
    ]
