# Generated by Django 4.1.4 on 2023-01-10 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_product_category'),
        ('main_app', '0012_profile_user'),
    ]

    operations = [
    ]
