# Generated by Django 4.1.4 on 2023-01-11 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_merge_0011_product_category_0012_profile_user'),
        ('main_app', '0013_product_user'),
    ]

    operations = [
    ]
